sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPCmE7wKF3qRKwkJmQx
    access-key-secret: 5ikCNbLwCl25ESXN4sUnNuPbAK0v2s
    bucket-name: sky-take-out-zhenght
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx409d0422048fa83a
    secret: 7c6473aeabc1abc85d3a0e3d649134ae



